apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: todo-app
spec:
  selector:
    app: postgres
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432