apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-configmap
  namespace: todo-app
data:
  init.sql: |
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = 'tododb') THEN
            CREATE DATABASE tododb;
        END IF;
    END $$;

    CREATE TABLE IF NOT EXISTS todo(
      todo_id SERIAL PRIMARY KEY,
      description VARCHAR(255)
    );

